# Generated by Django 2.1.5 on 2019-05-29 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='ISO 639 code (max 10 characters)', max_length=10)),
                ('name', models.CharField(db_index=True, help_text='Test set name (max 200 characters)', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TestSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Test set name (max 200 characters)', max_length=200)),
            ],
        ),
    ]
