# Generated by Django 2.2.1 on 2019-08-28 13:47
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [('leaderboard', '0001_initial')]

    operations = [
        migrations.AddField(
            model_name='testset',
            name='json_data',
            field=models.TextField(
                help_text='JSON data for test set', null=True
            ),
        )
    ]
