# Generated by Django 2.2.1 on 2019-08-31 08:13
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [('leaderboard', '0003_submission')]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='is_primary',
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text='Is primary sumission?',
            ),
        ),
        migrations.AddField(
            model_name='submission',
            name='score',
            field=models.FloatField(
                blank=True,
                db_index=True,
                help_text='SacreBLEU score',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='submission',
            name='sgml_file',
            field=models.FileField(
                help_text='SGML file containing submission output',
                null=True,
                upload_to='submissions',
            ),
        ),
    ]
