# Generated by Django 2.2.1 on 2020-06-19 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('leaderboard', '0005_auto_20200618_2157')]

    operations = [
        migrations.RemoveField(model_name='testset', name='sgml_file'),
        migrations.AddField(
            model_name='testset',
            name='ref_sgml_file',
            field=models.FileField(
                help_text='SGML file containing test set reference text',
                null=True,
                upload_to='testsets',
            ),
        ),
        migrations.AddField(
            model_name='testset',
            name='src_sgml_file',
            field=models.FileField(
                help_text='SGML file containing test set source text',
                null=True,
                upload_to='testsets',
            ),
        ),
    ]
