# pylint: disable=invalid-name,missing-docstring,protected-access
# Generated by Django 2.2.13 on 2020-06-23 23:29
import django.db.models.deletion
from django.db import migrations
from django.db import models

import leaderboard.models


class Migration(migrations.Migration):

    dependencies = [('leaderboard', '0011_auto_20200622_2334')]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='original_name',
            field=models.CharField(
                default='undefined',
                editable=False,
                help_text='Original file name (max 200 characters)',
                max_length=200,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submission',
            name='submitted_by',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to='leaderboard.Team',
            ),
        ),
        migrations.AlterField(
            model_name='submission',
            name='sgml_file',
            field=models.FileField(
                help_text='SGML file containing submission output',
                null=True,
                upload_to=leaderboard.models._get_submission_upload_path,
            ),
        ),
    ]
