# pylint: disable=invalid-name,missing-docstring
# Generated by Django 2.2.13 on 2020-06-24 02:28
from django.db import migrations
from django.db import models

import leaderboard.models


class Migration(migrations.Migration):
    dependencies = [('leaderboard', '0012_auto_20200623_1629')]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='token',
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=10,
                unique=True,
                validators=[leaderboard.models.validate_token],
            ),
        )
    ]
