# Generated by Django 2.2.13 on 2020-06-25 15:41
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0013_auto_20200623_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='score_chrf',
            field=models.FloatField(
                blank=True,
                db_index=True,
                help_text='chrF score',
                null=True,
            ),
        ),
    ]
