# pylint: disable=invalid-name,missing-docstring,protected-access
# Generated by Django 2.2.13 on 2020-06-26 20:41
from django.db import migrations
from django.db import models

import leaderboard.models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0014_submission_score_chrf'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='is_flagged',
            field=models.BooleanField(
                db_index=True, default=False, help_text='Is flagged?'
            ),
        ),
        migrations.AddField(
            model_name='team',
            name='is_removed',
            field=models.BooleanField(
                db_index=True, default=False, help_text='Is removed?'
            ),
        ),
        migrations.AlterField(
            model_name='submission',
            name='sgml_file',
            field=models.FileField(
                help_text='SGML file containing submission output',
                null=True,
                upload_to=leaderboard.models._get_submission_upload_path,
                validators=[leaderboard.models.validate_sgml_schema],
            ),
        ),
        migrations.AlterField(
            model_name='team',
            name='is_active',
            field=models.BooleanField(
                db_index=True, default=False, help_text='Is active?'
            ),
        ),
        migrations.AlterField(
            model_name='team',
            name='is_verified',
            field=models.BooleanField(
                db_index=True, default=False, help_text='Is verified?'
            ),
        ),
    ]
