# pylint: disable=invalid-name,missing-docstring
# Generated by Django 2.2.13 on 2020-07-01 18:52
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ('leaderboard', '0016_auto_20200626_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='is_constrained',
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text='Is constrained sumission?',
            ),
        ),
    ]
