# pylint: disable=invalid-name,missing-docstring
# Generated by Django 2.2.13 on 2020-07-10 20:37
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0018_team_publication_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testset',
            old_name='ref_sgml_file',
            new_name='ref_file',
        ),
        migrations.RenameField(
            model_name='testset',
            old_name='src_sgml_file',
            new_name='src_file',
        ),
        migrations.AddField(
            model_name='testset',
            name='file_format',
            field=models.CharField(
                choices=[('SGML', 'SGML format'), ('TEXT', 'Text format')],
                default='SGML',
                max_length=4,
            ),
        ),
        migrations.AlterField(
            model_name='testset',
            name='ref_file',
            field=models.FileField(
                blank=True,
                help_text='SGML or text file containing test set reference',
                null=True,
                upload_to='testsets',
            ),
        ),
        migrations.AlterField(
            model_name='testset',
            name='src_file',
            field=models.FileField(
                blank=True,
                help_text='SGML or text file containing test set source',
                null=True,
                upload_to='testsets',
            ),
        ),
    ]
