# pylint: disable=invalid-name,missing-docstring,protected-access
# Generated by Django 2.2.13 on 2020-07-10 21:45
from django.db import migrations
from django.db import models

import leaderboard.models


class Migration(migrations.Migration):
    dependencies = [
        ('leaderboard', '0019_auto_20200710_2037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='sgml_file',
            new_name='hyp_file',
        ),
        migrations.AddField(
            model_name='submission',
            name='file_format',
            field=models.CharField(
                choices=[('SGML', 'SGML format'), ('TEXT', 'Text format')],
                default='SGML',
                max_length=4,
            ),
        ),
        migrations.AlterField(
            model_name='submission',
            name='hyp_file',
            field=models.FileField(
                help_text='SGML or text file containing submission output',
                null=True,
                upload_to=leaderboard.models._get_submission_upload_path,
                validators=[leaderboard.models.validate_sgml_schema],
            ),
        ),
    ]
