# pylint: disable=invalid-name,missing-docstring
# Generated by Django 3.1.6 on 2021-02-11 11:50
from django.db import migrations
from django.db import models

import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0021_auto_20200710_2245'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        db_index=True,
                        help_text='Competition name (max 200 characters)',
                        max_length=200,
                        unique=True,
                    ),
                ),
                (
                    'description',
                    models.TextField(
                        help_text='Competition description (max 2000 characters)',
                        max_length=2000,
                    ),
                ),
                (
                    'deadline',
                    models.DateTimeField(
                        blank=True,
                        help_text='Competition deadline (max 2000 characters)',
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name='testset',
            name='competition',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='test_sets',
                related_query_name='test_sets',
                to='leaderboard.competition',
            ),
        ),
    ]
