# pylint: disable=invalid-name,missing-docstring
# Generated by Django 3.1.6 on 2021-02-11 12:48
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0022_competition'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='is_active',
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text='Is active competition?',
            ),
        ),
    ]
