# Generated by Django 3.1.7 on 2021-02-25 11:18
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0023_competition_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='start_time',
            field=models.DateTimeField(
                blank=True, help_text='Competition start time', null=True
            ),
        ),
        migrations.AlterField(
            model_name='competition',
            name='deadline',
            field=models.DateTimeField(
                blank=True, help_text='Competition deadline'
            ),
        ),
    ]
