# Generated by Django 3.1.7 on 2021-02-25 19:54
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0024_auto_20210225_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='deadline',
            field=models.DateTimeField(
                blank=True,
                help_text='Competition deadline (an empty value means no deadline)',
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='competition',
            name='start_time',
            field=models.DateTimeField(
                blank=True,
                help_text='Competition start time (an empty value means no start time)',
                null=True,
            ),
        ),
    ]
