# Generated by Django 3.1.7 on 2021-06-09 08:18
from django.db import migrations
from django.db import models

import leaderboard.models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0026_auto_20210226_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(
                db_index=True,
                help_text='Language name (max 200 characters)',
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name='submission',
            name='file_format',
            field=models.CharField(
                choices=[
                    ('SGML', 'SGML format'),
                    ('TEXT', 'Text format'),
                    ('XML', 'XML format'),
                ],
                default='TEXT',
                max_length=4,
            ),
        ),
        migrations.AlterField(
            model_name='submission',
            name='hyp_file',
            field=models.FileField(
                help_text='SGML, XML or text file containing submission output',
                null=True,
                upload_to=leaderboard.models._get_submission_upload_path,
                validators=[leaderboard.models.validate_sgml_schema],
            ),
        ),
        migrations.AlterField(
            model_name='testset',
            name='file_format',
            field=models.CharField(
                choices=[
                    ('SGML', 'SGML format'),
                    ('TEXT', 'Text format'),
                    ('XML', 'XML format'),
                ],
                default='XML',
                max_length=4,
            ),
        ),
        migrations.AlterField(
            model_name='testset',
            name='ref_file',
            field=models.FileField(
                blank=True,
                help_text='SGML, XML or text file containing test set reference(s)',
                null=True,
                upload_to='testsets',
                validators=[leaderboard.models.validate_xml_ref_testset],
            ),
        ),
        migrations.AlterField(
            model_name='testset',
            name='src_file',
            field=models.FileField(
                blank=True,
                help_text='SGML, XML or text file containing test set source',
                null=True,
                upload_to='testsets',
                validators=[leaderboard.models.validate_xml_src_testset],
            ),
        ),
    ]
