# Generated by Django 3.1.7 on 2021-06-11 07:13
from django.db import migrations
from django.db import models

import leaderboard.models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0028_auto_20210609_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='hyp_file',
            field=models.FileField(
                help_text='SGML, XML or text file containing submission output',
                null=True,
                upload_to=leaderboard.models._get_submission_upload_path,
                validators=[
                    leaderboard.models.validate_sgml_schema,
                    leaderboard.models.validate_xml_submission,
                ],
            ),
        ),
    ]
