# Generated by Django 3.1.7 on 2021-06-15 17:58
from django.db import migrations
from django.db import models

import leaderboard.models


class Migration(migrations.Migration):
    dependencies = [
        ('leaderboard', '0029_auto_20210611_0713'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='institution_name',
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text='Institution name (max 32 characters)',
                max_length=200,
                validators=[leaderboard.models.validate_institution_name],
            ),
        ),
        migrations.AlterField(
            model_name='team',
            name='publication_name',
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text='Team publication name (max 32 characters)',
                max_length=200,
                validators=[leaderboard.models.validate_publication_name],
            ),
        ),
    ]
