# Generated by Django 3.2.14 on 2022-07-21 23:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('leaderboard', '0032_testset_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='testset',
            name='compute_scores',
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text='Compute automatic scores?',
            ),
        ),
    ]
