# Generated by Django 4.2.3 on 2023-07-14 11:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leaderboard", "0033_testset_compute_scores"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="is_valid",
            field=models.BooleanField(
                db_index=True, default=False, help_text="Is valid?"
            ),
        ),
    ]
