# Generated by Django 4.2.3 on 2023-07-17 11:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leaderboard", "0034_submission_is_valid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="file_format",
            field=models.CharField(
                choices=[
                    ("SGML", "SGML format"),
                    ("TEXT", "Text format"),
                    ("XML", "XML format"),
                ],
                default="XML",
                max_length=4,
            ),
        ),
    ]
