# Generated by Django 4.2.3 on 2023-07-17 11:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leaderboard", "0035_alter_submission_file_format"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="is_contrastive",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Is contrastive submission?",
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="is_withdrawn",
            field=models.BooleanField(
                db_index=True, default=False, help_text="Is withdrawn?"
            ),
        ),
    ]
