# Generated by Django 3.1.7 on 2024-06-28 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0036_submission_is_contrastive_submission_is_withdrawn'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='is_open_source',
            field=models.BooleanField(db_index=True, default=False, help_text='Is open-source submission?'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='is_constrained',
            field=models.BooleanField(db_index=True, default=False, help_text='Is constrained submission?'),
        ),
    ]
