# Generated by Django 4.2.22 on 2025-06-17 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("leaderboard", "0038_alter_submission_file_format_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testset",
            name="source_language",
            field=models.ForeignKey(
                blank=True,
                help_text="Source language (optional for multi-language test sets)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="source_language_set",
                to="leaderboard.language",
            ),
        ),
        migrations.AlterField(
            model_name="testset",
            name="target_language",
            field=models.ForeignKey(
                blank=True,
                help_text="Target language (optional for multi-language test sets)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="target_language_set",
                to="leaderboard.language",
            ),
        ),
    ]
