# Generated by Django 4.2.22 on 2025-06-17 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leaderboard", "0039_make_test_set_languages_optional"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="is_verified",
            field=models.BooleanField(
                db_index=True, default=True, help_text="Is verified?"
            ),
        ),
    ]
