# Generated by Django 4.2.22 on 2025-06-23 22:17

from django.db import migrations, models
import leaderboard.models


class Migration(migrations.Migration):

    dependencies = [
        ("leaderboard", "0040_alter_team_is_verified"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="hyp_file",
            field=models.FileField(
                help_text="XML, JSONL (optionally compressed as .jsonl.gz) or text file containing submission output",
                null=True,
                upload_to=leaderboard.models._get_submission_upload_path,
                validators=[
                    leaderboard.models.validate_sgml_schema,
                    leaderboard.models.validate_xml_submission,
                    leaderboard.models.validate_jsonl_submission,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="testset",
            name="ref_file",
            field=models.FileField(
                blank=True,
                help_text="XML, JSONL (optionally compressed as .jsonl.gz) or text file containing test set reference(s)",
                null=True,
                upload_to="testsets",
                validators=[
                    leaderboard.models.validate_xml_ref_testset,
                    leaderboard.models.validate_jsonl_ref_testset,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="testset",
            name="src_file",
            field=models.FileField(
                blank=True,
                help_text="XML, JSONL (optionally compressed as .jsonl.gz) or text file containing test set source",
                null=True,
                upload_to="testsets",
                validators=[
                    leaderboard.models.validate_xml_src_testset,
                    leaderboard.models.validate_jsonl_src_testset,
                ],
            ),
        ),
    ]
