# Generated by Django 4.2.22 on 2025-06-24 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "leaderboard",
            "0041_alter_submission_hyp_file_alter_testset_ref_file_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="testset",
            name="validate",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="Validate submissions for this test set? Set to False to skip validation",
            ),
        ),
    ]
