# Generated by Django 4.2.22 on 2025-06-24 21:33

from django.db import migrations, models
import leaderboard.models


class Migration(migrations.Migration):

    dependencies = [
        ("leaderboard", "0042_testset_validate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="file_format",
            field=models.CharField(
                choices=[
                    ("SGML", "SGML format"),
                    ("TEXT", "Text format"),
                    ("XML", "XML format"),
                    ("JSONL", "JSONL format"),
                    ("JSON", "JSON format"),
                ],
                default="XML",
                max_length=5,
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="hyp_file",
            field=models.FileField(
                help_text="Submission file containing system output",
                null=True,
                upload_to=leaderboard.models._get_submission_upload_path,
                validators=[
                    leaderboard.models.validate_sgml_schema,
                    leaderboard.models.validate_xml_submission,
                    leaderboard.models.validate_jsonl_submission,
                    leaderboard.models.validate_json_submission,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="testset",
            name="file_format",
            field=models.CharField(
                choices=[
                    ("SGML", "SGML format"),
                    ("TEXT", "Text format"),
                    ("XML", "XML format"),
                    ("JSONL", "JSONL format"),
                    ("JSON", "JSON format"),
                ],
                default="XML",
                max_length=5,
            ),
        ),
        migrations.AlterField(
            model_name="testset",
            name="ref_file",
            field=models.FileField(
                blank=True,
                help_text="XML, JSONL (optionally compressed as .jsonl.gz), JSON (optionally compressed as .json.gz) or text file containing test set reference(s)",
                null=True,
                upload_to="testsets",
                validators=[
                    leaderboard.models.validate_xml_ref_testset,
                    leaderboard.models.validate_jsonl_ref_testset,
                    leaderboard.models.validate_json_ref_testset,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="testset",
            name="src_file",
            field=models.FileField(
                blank=True,
                help_text="XML, JSONL (optionally compressed as .jsonl.gz), JSON (optionally compressed as .json.gz) or text file containing test set source",
                null=True,
                upload_to="testsets",
                validators=[
                    leaderboard.models.validate_xml_src_testset,
                    leaderboard.models.validate_jsonl_src_testset,
                    leaderboard.models.validate_json_src_testset,
                ],
            ),
        ),
    ]
