# Generated by Django 4.2.22 on 2025-06-24 22:34

from django.db import migrations, models
import leaderboard.models


class Migration(migrations.Migration):

    dependencies = [
        ("leaderboard", "0043_alter_submission_file_format_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="publication_name",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Team short name (max 32 characters)",
                max_length=200,
                validators=[leaderboard.models.validate_publication_name],
            ),
        ),
    ]
