name: "OCELoT"

on: [push, pull_request]

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Python Code Validator
        uses: cfedermann/python-code-validator@master
  testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install requirements
        run: python3 -m pip install -r requirements.txt
      - name: Run unit tests
        run: python3 manage.py test -v2
